// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eknwrmkewwpkztszqflt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbndybWtld3dwa3p0c3pxZmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjEzNDIsImV4cCI6MjA2MzU5NzM0Mn0.lnj4PbO7gAX1AEACiDivwcXvCwxflgZVdRHYPV0ORko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);